CREATE DATABASE hothothot

CREATE TABLE sensors (
	id INT AUTO_INCREMENT NOT NULL,
	name VARCHAR(50) NOT NULL,
	type VARCHAR(50) NOT NULL,
	url VARCHAR(255) NOT NULL )

CREATE TABLE data_sensors (
	id INT AUTO_INCREMENT NOT NULL,
	value FLOAT NOT NULL
	timestamp TIMESTAMP NOT NULL,
	sensor_id INT NOT NULL,
	FOREIGN KEY (sensor_id) REFERENCES sensors (id) ON DELETE CASCADE
)


